### PR TITLE
make repo suitable for RN 0.28

### LINKED ISSUE #9: ActivityIndicatorIOS has been deprecated in 0.28.0

### PR DESCRIPTION
**Pull request by fabianbormann**
closes #9

### CODE REVIEW

**Comment by tlenclos** [comment]
👍

**Comment by evollu** [comment]
I get warning for android `Circular indetermitnate ProgressBarAndroid is deprecated. User ActivityIndicator instead in 0.28 too. Can you make change for that too?

**Comment by fabianbormann** [comment]
Yeeaahhh 😁  .... I saw that, too but the "solution" for this task would be to replace:

``` Javascript
    if (Platform.OS === 'android') {
      return (
        <ProgressBarAndroid 
          style={{
            height: 20,
          }}
          styleAttr="Inverse"
          {...this.props}
        />
      );
    } else {
      return (
        <ActivityIndicator
          animating={true}
          size="small"
          {...this.props}
        />
      );
```

with 

``` Javascript
    if (Platform.OS === 'android') {
      return (
        <ActivityIndicator
          animating={true}
          size="small"
          {...this.props}
        />
      );
    } else {
      return (
        <ActivityIndicator
          animating={true}
          size="small"
          {...this.props}
        />
      );
    }
```

which is the same like

``` Javascript
  render() {
    return (
      <View>
          <ActivityIndicator
          animating={true}
          size="small"
          {...this.props}
        />
      </View>
    );
  },
```

So I think this Repo is a great workaround for RN < 0.28 but for RN >= 0.28 you could simply use the RN ActivityIndicator module and there is no need for third party modules anymore😉

**Comment by evollu** [comment]
exactly

**Comment by FaridSafi** [comment]
thank you @fabianbormann

**Pull request merged**
